---
- name: cgroups
  become: true
  hosts: all
  vars:
    packages:
      - daemonize
      - stress
    count: 1
  tasks:
    - yum:
        name: "{{ packages }}"
        state: latest
    - template:
        src: ../templates/stress.service.j2
        dest: /etc/systemd/system/stress1.service
    - systemd:
        name: stress1.service
        state: started
        enabled: no
